// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yisbltqhpnsnzfiioqmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpc2JsdHFocG5zbnpmaWlvcW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMzU0NjEsImV4cCI6MjA3OTkxMTQ2MX0.gzxozZw-l2am5k9jXdmMbwA8pO-U97Kmgy-is1Mf88g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});